workspace = { members = ["pigpiod_if2-sys"] }
[package]
name = "cps"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.155"
pigpiod_if2 = { version = "0.1.0", path = "pigpiod_if2-sys", package = "pigpiod_if2-sys" }
